apt-snapshot-expiry: exit with error if any snapshot will expire within 1 month.

diff --git a/bin/apt-snapshots-expiry b/bin/apt-snapshots-expiry
--- a/bin/apt-snapshots-expiry
+++ b/bin/apt-snapshots-expiry
@@ -2,6 +2,7 @@
 
 set -eu
 
+FAILURE=no
 for dir in config/APT_snapshots.d vagrant/definitions/tails-builder/config/APT_snapshots.d; do
     set -eu
     echo "${dir:?}:"
@@ -27,7 +28,18 @@ for dir in config/APT_snapshots.d vagrant/definitions/tails-builder/config/APT_s
             esac
             EXPIRY="$(curl --silent "https://time-based.snapshots.deb.tails.boum.org/${ARCHIVE:?}/dists/${DIST:?}/snapshots/${SERIAL:?}/Release" | sed -n 's/^Valid-Until:\s\+\(.*\)$/\1/p')"
         fi
-        echo "* Archive '${ARCHIVE:?}' uses snapshot '${SERIAL:?}' which expires on: ${EXPIRY:?}"
+        STATUS="archive '${ARCHIVE:?}' uses snapshot '${SERIAL:?}' which expires on: ${EXPIRY:?}"
+        if [ "${EXPIRY}" = 'never' ] || \
+           [ "$(date -d "${EXPIRY}" +%s)" -ge "$(date -d "now + 1 month" +%s)" ]; then
+            echo "OK:   ${STATUS}"
+        else
+            FAILURE=yes
+            echo "FAIL: ${STATUS}, which is within one month!" >&2
+        fi
     done
     echo ---
 done
+
+if [ "${FAILURE}" = yes ]; then
+    exit 1
+fi
