simplify pre-commit-translation hook.

diff --git a/bin/pre-commit-translation b/bin/pre-commit-translation
--- a/bin/pre-commit-translation
+++ b/bin/pre-commit-translation
@@ -8,27 +8,12 @@
 set -e
 set -u
 
-if git rev-parse --verify HEAD >/dev/null 2>&1
-then
-    against=HEAD
-else
-    # Initial commit: diff against an empty tree object
-    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
-
 path=$(git rev-parse --show-toplevel)
 
-# Redirect output to stderr.
-exec 1>&2
-
-STAGED_PO_FILES=$(git diff --ignore-submodules --name-only --cached --diff-filter=d -- '*.po' $against | grep '^wiki/' | tr '\n' ' ')
-
 # If we try to commit po files, check that they do not contain errors.
-if ! [ -z  "$STAGED_PO_FILES" ] ; then
-    if ! "${path}/submodules/jenkins-tools/slaves/check_po" ${STAGED_PO_FILES}; then
-        echo
-        echo "The po files you're trying to commit contain errors. Please fix them and try again."
-        echo
-        exit 1
-    fi
+if ! "${path}/wiki/src/contribute/l10n_tricks/unifyPo" --cached; then
+	echo
+	echo "The po files you're trying to commit contain errors. Please fix them and try again."
+	echo
+	exit 1
 fi
