release script: do not auto-{commit,tag} the release, some more work needs to be done first

diff --git a/release b/release
--- a/release
+++ b/release
@@ -63,12 +63,12 @@ git-dch \
    || fatal "git-dch failed."
 
 # commit and tag the release
-if [ "${SNAPSHOT}" = no ]; then
-   echo "Commit'ing debian/changelog..."
-   git commit -m "releasing version ${NEW_VERSION}" debian/changelog \
-      || fatal "failed to commit debian/changelog"
-   echo "Tagging new version..."
-   git tag -u "${AMNESIA_DEV_KEYID}" -m "tagging version ${NEW_VERSION}" "${NEW_VERSION}"
-fi
+# if [ "${SNAPSHOT}" = no ]; then
+#    echo "Commit'ing debian/changelog..."
+#    git commit -m "releasing version ${NEW_VERSION}" debian/changelog \
+#       || fatal "failed to commit debian/changelog"
+#    echo "Tagging new version..."
+#    git tag -u "${AMNESIA_DEV_KEYID}" -m "tagging version ${NEW_VERSION}" "${NEW_VERSION}"
+# fi
 
 echo "done."
