Simplify.

diff --git a/run_test_suite b/run_test_suite
--- a/run_test_suite
+++ b/run_test_suite
@@ -88,11 +88,14 @@ error() {
     exit 1
 }
 
-check_dependency() {
-    if ! which "${1}" >/dev/null && \
-       ! dpkg -s "${1}" 2>/dev/null | grep -q "^Status:.*installed"; then
-        error "'${1}' is missing, please install it and run again. Aborting..."
-    fi
+check_dependencies() {
+    while [ -n "${1:-}" ]; do
+        if ! which "${1}" >/dev/null && \
+           ! dpkg -s "${1}" 2>/dev/null | grep -q "^Status:.*installed"; then
+            error "'${1}' is missing, please install it and run again. Aborting..."
+        fi
+        shift
+    done
 }
 
 display_in_use() {
@@ -122,7 +125,7 @@ start_xvfb() {
 }
 
 start_vnc_server() {
-    check_dependency x11vnc
+    check_dependencies x11vnc
     VNC_SERVER_PORT="$(x11vnc -listen localhost -display ${TARGET_DISPLAY} \
                               -bg -nopw 2>&1 | \
                                   grep -m 1 "^PORT=[0-9]\+" | sed 's/^PORT=//')"
@@ -130,13 +133,12 @@ start_vnc_server() {
 }
 
 start_vnc_viewer() {
-    check_dependency xtightvncviewer
+    check_dependencies xtightvncviewer
     xtightvncviewer -viewonly localhost:${VNC_SERVER_PORT} 1>/dev/null 2>&1 &
 }
 
 capture_session() {
-    check_dependency ffmpeg
-    check_dependency libvpx1
+    check_dependencies ffmpeg libvpx1
     echo "Capturing guest display into ${CAPTURE_FILE}"
     ffmpeg -f x11grab -s 1024x768 -r 15 -i ${TARGET_DISPLAY}.0 -an \
         -vcodec libvpx -y "${CAPTURE_FILE}" >/dev/null 2>&1 &
@@ -233,9 +235,7 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-for dep in ${GENERAL_DEPENDENCIES}; do
-    check_dependency "${dep}"
-done
+check_dependencies ${GENERAL_DEPENDENCIES}
 
 TARGET_DISPLAY=$(next_free_display)
 
