Make it possible to run @source tests on current Debian sid.

diff --git a/run_test_suite b/run_test_suite
--- a/run_test_suite
+++ b/run_test_suite
@@ -195,10 +195,15 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-for dep in ffmpeg git libvirt-bin libvirt-dev libavcodec-extra-53 libvpx1 \
+for dep in ffmpeg git libvirt-bin libvirt-dev libvpx1 \
            virt-viewer libsikuli-script-java ovmf tcpdump xvfb; do
     check_dependency "${dep}"
 done
+
+package_installed libavcodec-extra-53 \
+    || package_installed libav-tools \
+    || error "Both libavcodec-extra-53 and libav-tools, are missing, " \
+	     "please install one of those and run again. Aborting..."
 
 TARGET_DISPLAY=$(next_free_display)
 
