Vagrant: only clean up apt-cacher-ng if it was used.

diff --git a/vagrant/provision/setup-tails-builder b/vagrant/provision/setup-tails-builder
--- a/vagrant/provision/setup-tails-builder
+++ b/vagrant/provision/setup-tails-builder
@@ -84,7 +84,14 @@ done
 # Clean up
 apt-get -y autoremove
 apt-get -y clean
-perl /usr/lib/apt-cacher-ng/expire-caller.pl || echo "The clean-up of apt-cacher-ng's cache failed: this is not fatal and most likely just means that some disk space could not be reclaimed -- in order to fix that situation you need to manually investigate /var/log/apt-cacher-ng/main_*.html " >&2
+if [ "${TAILS_PROXY_TYPE}" = "vmproxy" ]; then
+    perl /usr/lib/apt-cacher-ng/expire-caller.pl ||
+        echo "The clean-up of apt-cacher-ng's cache failed: this is" \
+             "not fatal and most likely just means that some disk" \
+             "space could not be reclaimed -- in order to fix that" \
+             "situation you need to manually investigate " \
+             "/var/log/apt-cacher-ng/main_*.html" >&2
+fi
 
 # Necessary so that vagrant can merge the base branch
 git config --global user.name vagrant
