Don't modify files in the source tree before having possibly merged the base branch into it.
Previously, when building in Jenkins, we refreshed the wiki (twice) and
translations before merging the base branch. As a result, we're seeing build
failures with the "Your local changes to the following files would be
overwritten by merge" error message.

Let's now build the wiki and refresh translations only _after_ having merged the
base branch, which makes more sense anyway: we want to include changes from the
base branch into the wiki and translations. And while we're at it, let's refresh
the wiki only once when building in Jenkins.

Note that Vagrant builds will still build the wiki before setting up the ramdisk
and running live-build: those builds don't merge the base branch anyway, so they
can as well keep the wiki build caching mechanism, which is a nice optimization.

Will-fix: #9406

diff --git a/auto/build b/auto/build
--- a/auto/build
+++ b/auto/build
@@ -46,12 +46,6 @@ rm -rf cache/stages_rootfs
 # get LB_ARCHITECTURE and LB_DISTRIBUTION
 . config/bootstrap
 
-# build the doc wiki
-./build-wiki
-
-# refresh translations of our programs
-./refresh-translations || fatal "refresh-translations failed ($?)."
-
 # save variables that are needed by chroot_local-hooks
 echo "LB_DISTRIBUTION=${LB_DISTRIBUTION}" >> config/chroot_local-includes/usr/share/amnesia/build/variables
 echo "POTFILES_DOT_IN='$(
@@ -132,6 +126,12 @@ if [ -n "$JENKINS_URL" ] && [ -z "$GIT_TAG" ] \
     BUILD_BASENAME="${BUILD_BASENAME}+${CLEAN_GIT_BASE_BRANCH}"
     BUILD_BASENAME="${BUILD_BASENAME}@${GIT_BASE_BRANCH_SHORT_ID}"
 fi
+
+# build the doc wiki
+./build-wiki
+
+# refresh translations of our programs
+./refresh-translations || fatal "refresh-translations failed ($?)."
 
 case "$LB_BINARY_IMAGES" in
    iso)
