When building in Jenkins, merge its base branch into the branch being built.
... unless we're building from a tag, or from the base branch itself.

diff --git a/auto/build b/auto/build
--- a/auto/build
+++ b/auto/build
@@ -102,6 +102,27 @@ else
     fi
 fi
 
+GIT_BASE_BRANCH=$(head -n1 config/base_branch) \
+    || fatal "GIT_BASE_BRANCH could not be guessed."
+
+# Merge base branch into the branch being built, iff. we're building
+# in Jenkins, and not building from a tag, and not building the base
+# branch itself
+if [ -n "$JENKINS_URL" ] && [ -z "$GIT_TAG" ] \
+       && [ "$GIT_BRANCH" != "$GIT_BASE_BRANCH" ] ; then
+    GIT_BASE_BRANCH_COMMIT=$(git rev-parse "origin/${GIT_BASE_BRANCH}") \
+	|| fatal "Base branch's top commit could not be guessed."
+
+    cat > .git/info/attributes <<-EOF
+	config/APT_suites merge=union
+	EOF
+
+    echo "Merging base branch origin/${GIT_BASE_BRANCH}"
+    echo "(at commit ${GIT_BASE_BRANCH_COMMIT})..."
+    git merge --no-edit "origin/${GIT_BASE_BRANCH}" \
+	|| fatal "Failed to merge base branch."
+fi
+
 case "$LB_BINARY_IMAGES" in
    iso)
       BUILD_FILENAME_EXT=iso
