Make isohybrid failures fatal (refs: #12453).
So that issues such as #12453 don't go unnoticed anymore.

diff --git a/auto/build b/auto/build
--- a/auto/build
+++ b/auto/build
@@ -228,7 +228,7 @@ if [ -e "${BUILD_FILENAME}.${BUILD_FILENAME_EXT}" ]; then
        ISO_FILE="${BUILD_FILENAME}.${BUILD_FILENAME_EXT}"
        print_iso_size "$ISO_FILE"
        echo "Hybriding it..."
-       isohybrid $AMNESIA_ISOHYBRID_OPTS "$ISO_FILE"
+       isohybrid $AMNESIA_ISOHYBRID_OPTS "$ISO_FILE" || fatal "isohybrid failed"
        print_iso_size "$ISO_FILE"
        truncate -s %2048 "$ISO_FILE"
        print_iso_size "$ISO_FILE"
