auto/config: abort if tails-custom-apt-sources failed.
Currently the build of our devel branch fails in a confusing manner.

tails-custom-apt-sources fails this way:

 + tails-custom-apt-sources
 base_branch: testing
 current_branch: devel
 In a base branch, config/base_branch must match the current branch.

… but the build goes on, and fails later when we try installing packages
that are only found in our custom APT repository, because no APT source
pointing to that repository was set up.

Let's avoid this and fail earlier when we know the build can't possibly succeed.

diff --git a/auto/config b/auto/config
--- a/auto/config
+++ b/auto/config
@@ -176,7 +176,8 @@ if [ -e config/binary_rootfs/squashfs.sort ]; then
 fi
 
 # custom APT sources
-tails-custom-apt-sources > config/chroot_sources/tails.chroot
+tails-custom-apt-sources > config/chroot_sources/tails.chroot \
+   || fatal "tails-custom-apt-sources failed with exit code $?"
 
 # tails-transform-mirror-url and its dependencies
 install -m 0755 \
