Build system: shrink the apt-cacher-ng cache after a successful build too (refs: #17288)
7f0a1f0e42792cc715f28f8566c98fa1e6bacda3 moved this cache cleanup operation from
the provisioning script to build-tails, so it's run before each build. This is
great and improves things in most cases. But there's one situation in which
this change makes things worse:

1. Before build N, the cache was approaching the 10G limit.
2. Build N has filled the cache.
3. While we provision the VM for build N+1, APT operations fail:
   apt-cacher-ng returns a "503  OUT OF DISK SPACE" error.

To mitigate this, let's do garbage collection both before and after
a build.

diff --git a/vagrant/provision/assets/build-tails b/vagrant/provision/assets/build-tails
--- a/vagrant/provision/assets/build-tails
+++ b/vagrant/provision/assets/build-tails
@@ -64,6 +64,21 @@ ntp_synchronized() {
 	timedatectl status | grep -qs -E '^\s*System\s+clock\s+synchronized:\s+yes$'
 }
 
+shrink_acng_cache() {
+	local proxy_type="$1"
+	[ "${proxy_type}" = "vmproxy" ] || return 0
+	# The apt-cacher-ng cache disk is 15G, so let's ensure at most 10G
+	# of it is used there is 5G before each build, which should be
+	# enough for any build, even if we have to download a complete set
+	# of new packages for a new Debian release.
+	as_root_do /usr/lib/apt-cacher-ng/acngtool shrink 10G -f || \
+	echo "The clean-up of apt-cacher-ng's cache failed: this is" \
+	     "not fatal and most likely just means that some disk" \
+	     "space could not be reclaimed -- in order to fix that" \
+	     "situation you need to manually investigate " \
+	     "/var/cache/apt-cacher-ng/apt-cacher-ng-log/main_*.html" >&2
+}
+
 if [ "${TAILS_BUILD_FAILURE_RESCUE}" != 1 ]; then
 	trap cleanup EXIT
 	remove_build_dirs
@@ -142,18 +157,7 @@ if [ -n "$TAILS_DATE_OFFSET" ]; then
 	as_root_do timedatectl set-time "$DESIRED_DATE"
 fi
 
-if [ "${TAILS_PROXY_TYPE}" = "vmproxy" ]; then
-	# The apt-cacher-ng cache disk is 15G, so let's ensure at most 10G
-	# of it is used there is 5G before each build, which should be
-	# enough for any build, even if we have to download a complete set
-	# of new packages for a new Debian release.
-	as_root_do /usr/lib/apt-cacher-ng/acngtool shrink 10G -f || \
-	echo "The clean-up of apt-cacher-ng's cache failed: this is" \
-	     "not fatal and most likely just means that some disk" \
-	     "space could not be reclaimed -- in order to fix that" \
-	     "situation you need to manually investigate " \
-	     "/var/cache/apt-cacher-ng/apt-cacher-ng-log/main_*.html" >&2
-fi
+shrink_acng_cache "${TAILS_PROXY_TYPE}"
 
 BUILD_DIR=$(mktemp -d /tmp/tails-build.XXXXXXXX)
 if [ "${TAILS_RAM_BUILD}" ]; then
@@ -165,5 +169,7 @@ cd "${BUILD_DIR}"
 
 as_root_do lb config --cache false
 as_root_do lb build
+
+shrink_acng_cache "${TAILS_PROXY_TYPE}"
 
 mv -f tails-* "${TAILS_GIT_DIR}/"
