Make indentation consistent.
For some reason, this script is indented using tabs. But recent changes
introduced 4-spaces indentation. Let's fix that.

diff --git a/vagrant/provision/assets/build-tails b/vagrant/provision/assets/build-tails
--- a/vagrant/provision/assets/build-tails
+++ b/vagrant/provision/assets/build-tails
@@ -59,27 +59,28 @@ fi
 
 TAILS_GIT_DIR="/home/vagrant/amnesia"
 if [ ! -d "${TAILS_GIT_DIR}" ]; then
-    # We use --shared as an time/space optimization, and it is safe
-    # since our build process doesn't modify any objects (which would
-    # fail since the host's .git directory is shared read-only).
-    git clone --shared --local /amnesia.git/.git "${TAILS_GIT_DIR}"
-    # When we locally Git clone the main repo over the filesystem
-    # above, it will use the host's local repo as origin, but the
-    # submodules will continue to use their remote repos. A problem
-    # with this, beside unnecessary fetching of the network, is that
-    # any unpublished commits in the host's submodule are
-    # inaccessible, so if we want to build we first have to push those
-    # commits to the submodules remote repo. To avoid this, and in
-    # general try to make sure that the Git state in the builder is
-    # the same as on the host, we just clone the submodules in the
-    # same way we do the main repo.
-    (
-        cd "${TAILS_GIT_DIR}/submodules"
-        for submodule in $(ls -1); do
-            rm -rf "${submodule}"
-            git clone --shared "/amnesia.git/.git/modules/submodules/${submodule}"
-        done
-    )
+	# We use --shared as an time/space optimization, and it is safe
+	# since our build process doesn't modify any objects (which would
+	# fail since the host's .git directory is shared read-only).
+	git clone --shared --local /amnesia.git/.git "${TAILS_GIT_DIR}"
+	# When we locally Git clone the main repo over the filesystem
+	# above, it will use the host's local repo as origin, but the
+	# submodules will continue to use their remote repos. A problem
+	# with this, beside unnecessary fetching of the network, is that
+	# any unpublished commits in the host's submodule are
+	# inaccessible, so if we want to build we first have to push those
+	# commits to the submodules remote repo. To avoid this, and in
+	# general try to make sure that the Git state in the builder is
+	# the same as on the host, we just clone the submodules in the
+	# same way we do the main repo.
+	(
+		cd "${TAILS_GIT_DIR}/submodules"
+		for submodule in $(ls -1); do
+			rm -rf "${submodule}"
+			git clone --shared \
+			    "/amnesia.git/.git/modules/submodules/${submodule}"
+		done
+	)
 fi
 
 cd "${TAILS_GIT_DIR}"
@@ -120,16 +121,16 @@ if [ -n "$TAILS_DATE_OFFSET" ]; then
 fi
 
 if [ "${TAILS_PROXY_TYPE}" = "vmproxy" ]; then
-    # The apt-cacher-ng cache disk is 15G, so let's ensure at most 10G
-    # of it is used there is 5G before each build, which should be
-    # enough for any build, even if we have to download a complete set
-    # of new packages for a new Debian release.
-    as_root_do /usr/lib/apt-cacher-ng/acngtool shrink 10G -f || \
-        echo "The clean-up of apt-cacher-ng's cache failed: this is" \
-             "not fatal and most likely just means that some disk" \
-             "space could not be reclaimed -- in order to fix that" \
-             "situation you need to manually investigate " \
-             "/var/cache/apt-cacher-ng/apt-cacher-ng-log/main_*.html" >&2
+	# The apt-cacher-ng cache disk is 15G, so let's ensure at most 10G
+	# of it is used there is 5G before each build, which should be
+	# enough for any build, even if we have to download a complete set
+	# of new packages for a new Debian release.
+	as_root_do /usr/lib/apt-cacher-ng/acngtool shrink 10G -f || \
+	echo "The clean-up of apt-cacher-ng's cache failed: this is" \
+	     "not fatal and most likely just means that some disk" \
+	     "space could not be reclaimed -- in order to fix that" \
+	     "situation you need to manually investigate " \
+	     "/var/cache/apt-cacher-ng/apt-cacher-ng-log/main_*.html" >&2
 fi
 
 BUILD_DIR=$(mktemp -d /tmp/tails-build.XXXXXXXX)
