Fix 00-install-tailslib in case of multiple matches
Will-fix: #15421

diff --git a/config/chroot_local-hooks/00-install-tailslib b/config/chroot_local-hooks/00-install-tailslib
--- a/config/chroot_local-hooks/00-install-tailslib
+++ b/config/chroot_local-hooks/00-install-tailslib
@@ -15,11 +15,14 @@ ensure_hook_dependency_is_installed python3-setuptools
     python3 setup.py clean
     python3 setup.py install
 
+    # Strip nondeterministic information from tailslib
     package_glob_pattern="/usr/local/lib/python3.*/dist-packages/Tailslib*.egg"
-    if [ ! -f ${package_glob_pattern} ]; then
-       echo "Cannot find Tailslib Python package \"${package_glob_pattern}\"" >&2
-       exit 1
-    fi
-    strip_nondeterminism_wrapper --type zip ${package_glob_pattern} 2>/dev/null
+    for egg in ${package_glob_pattern}; do
+        if [ ! -f "${egg}" ]; then
+            echo "Cannot find Tailslib Python package \"${package_glob_pattern}\"" >&2
+            exit 1
+        fi
+        strip_nondeterminism_wrapper --type zip ${egg} 2>/dev/null
+    done
 )
 rm -rf /tmp/pythonlib
