Use a variable name that causes less side-effects.

diff --git a/config/chroot_local-hooks/14-add_localized_iceweasel_searchplugins b/config/chroot_local-hooks/14-add_localized_iceweasel_searchplugins
--- a/config/chroot_local-hooks/14-add_localized_iceweasel_searchplugins
+++ b/config/chroot_local-hooks/14-add_localized_iceweasel_searchplugins
@@ -15,15 +15,15 @@ locales_for_lang() {
 		sed -n -e "s/^langpack-\($locale\)\(-[A-Z]\+\)\?@iceweasel.mozilla.org.xpi/\1\2/p"
 }
 
-for LANG in $(find /usr/share/amnesia/iceweasel/searchplugins/locale -maxdepth 1 -type d -printf "%P\n"); do
-	LOCALES="$(locales_for_lang "$LANG")"
+for LANGUAGE in $(find /usr/share/amnesia/iceweasel/searchplugins/locale -maxdepth 1 -type d -printf "%P\n"); do
+	LOCALES="$(locales_for_lang "$LANGUAGE")"
 	if [ -z "$LOCALES" ]; then
-		echo "Unable to find a matching locale for $LANG." >&2
+		echo "Unable to find a matching locale for $LANGUAGE." >&2
 		exit 1
 	fi
 	for LOCALE in $LOCALES; do
 		mkdir -p /etc/iceweasel/searchplugins/locale/$LOCALE
-		for SEARCHPLUGIN in $(find "/usr/share/amnesia/iceweasel/searchplugins/locale/$LANG" -maxdepth 1 -type f); do
+		for SEARCHPLUGIN in $(find "/usr/share/amnesia/iceweasel/searchplugins/locale/$LANGUAGE" -maxdepth 1 -type f); do
 			ln -s "$SEARCHPLUGIN" /etc/iceweasel/searchplugins/locale/$LOCALE
 		done
 	done
