Make error message correctly reflect what we're checking for (refs: #12551)

diff --git a/config/chroot_local-hooks/31-gdm-tails b/config/chroot_local-hooks/31-gdm-tails
--- a/config/chroot_local-hooks/31-gdm-tails
+++ b/config/chroot_local-hooks/31-gdm-tails
@@ -27,7 +27,7 @@ create_tails_session_file() {
             "^RequiredComponents=org\.gnome\.Shell" "${TAILS_SESSION_FILE}" || \
        ! grep -q --fixed-strings --line-regexp \
             "Name=GNOME Classic" "${TAILS_SESSION_FILE}"; then
-        echo "Couldn't find expected exec line in GNOME's session file:" >&2
+        echo "Couldn't find expected Name and RequiredComponents lines in GNOME's session file:" >&2
         echo "(${TAILS_SESSION_FILE})" >&2
         exit 1
     fi
