Ensure we stop shipping RTL8822BE/RTL8822CE firmware once it's in Debian (refs: #17323)
Once those files are in Debian and they get updated there, if we don't notice
this warning, we'll be shipping outdated firmware, which is not ideal.

I'm concerned that this warning will be hard to spot in the middle of
a 15k-lines build log, that has 30+ other warnings which are all
false positives.

So let's abort the build whenever we detect this situation.

diff --git a/config/chroot_local-hooks/49-fix-missing-rtw88-firmware b/config/chroot_local-hooks/49-fix-missing-rtw88-firmware
--- a/config/chroot_local-hooks/49-fix-missing-rtw88-firmware
+++ b/config/chroot_local-hooks/49-fix-missing-rtw88-firmware
@@ -30,6 +30,7 @@ for file in $FILES; do
     echo "=> Missing firmware ($file), copying"
     cp "$orig_dir/$file" "$path"
   else
-    echo "=> WARNING: Firmware for $file found, maybe this hook could be dropped"
+    echo "=> ERROR: Firmware for $file found, maybe this hook could be dropped"
+    exit 1
   fi
 done
