More precise error message on rename error.

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -272,7 +272,7 @@ activate_volumes ()
 			   [ -n "$(getfacl --omit-header --skip-base "$f")" ]
 			then
 				mv "$f" "${f}.disabled" \
-					|| error "Failed to disable unsafe live-additional-software.conf: $?"
+					|| error "Failed to disable unsafe '$f': $?"
 			fi
 		done
 		# Migrate known-safe settings from old configuration to new one.
