Only disable live-additional-software.conf if it was not migrated yet, and do it earlier.
Let's at least have unsafe configuration files disabled, even in cases when the
following steps fail.

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -240,6 +240,15 @@ activate_volumes ()
 			|| error "Could not chown /live/persistence/*_unlocked"
 		chmod 1777 /live/persistence/*_unlocked \
 			|| error "Could not chmod /live/persistence/*_unlocked"
+		# Disable live-additional-software.conf if it was not migrated yet.
+		for f in /live/persistence/*_unlocked/live-additional-software.conf
+		do
+			if [ $(stat -c %U "$f") = amnesia ]
+			then
+				mv "$f" "${f}.disabled" \
+					|| error "Failed to disable unsafe live-additional-software.conf: $?"
+			fi
+		done
 		# Migrate known-safe settings from old configuration to new one.
 		for old_conf in /live/persistence/*_unlocked/live-persistence.conf
 		do
@@ -267,11 +276,6 @@ activate_volumes ()
 			-name persistence.conf -o -name live-*.conf \
 			-exec chmod 0600 {} \; \
 			|| error "Failed to chown persistence.conf and live-*.conf: $?"
-		# Disable live-additional-software.conf if XXX
-		find /live/persistence/*_unlocked/ -mindepth 1 -maxdepth 1 \
-			-name live-additional-software.conf \
-			-exec mv {} {}.disabled \; \
-			|| error "Failed to disable live-additional-software.conf: $?"
 		# Load the new persistence.conf.
 		get_custom_mounts ${custom_mounts} ${open_volumes}
 	fi
