live-persist: move error() function before the first potential usecase.

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+error ()
+{
+	echo "error: ${@}" >&2
+	exit 1
+}
+
 # import Cmdline()
 . /lib/live/boot/cmdline.sh
 
@@ -59,12 +65,6 @@ Options affecting the 'activate' action:
 warning ()
 {
 	echo "warning: ${@}" >&2
-}
-
-error ()
-{
-	echo "error: ${@}" >&2
-	exit 1
 }
 
 dbus_udisks_get_attribute ()
