Use argument joining instead of expansion
Suggested-by: ShellCheck
Documentation: https://www.shellcheck.net/wiki/SC2145

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -2,13 +2,13 @@
 
 error ()
 {
-	echo "error: ${@}" >&2
+	echo "error: ${*}" >&2
 	exit 1
 }
 
 warning ()
 {
-	echo "warning: ${@}" >&2
+	echo "warning: ${*}" >&2
 }
 
 # import Cmdline_old()
