Always set correct ownership, permissions and ACL on the persistence root.

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -229,17 +229,28 @@ activate_volumes ()
 	get_custom_mounts ${custom_mounts} ${open_volumes}
 	# ... and now the persistent volumes should be mounted.
 
+	# Enable the acl mount option on all persistent filesystems.
+	for mountpoint in /live/persistence/*_unlocked
+	do
+		mount -o remount,acl "$mountpoint"
+	done
+
+	# Set correct ownership, permissions and ACLs on the filesystems root.
+	chown root:root /live/persistence/*_unlocked \
+		|| error "Could not chown /live/persistence/*_unlocked: $?"
+	chmod 0775 /live/persistence/*_unlocked \
+		|| error "Could not chmod /live/persistence/*_unlocked: $?"
+	setfacl -b /live/persistence/*_unlocked \
+		|| error "Could not clear ACL on /live/persistence/*_unlocked: $?"
+	setfacl -m user:tails-persistence-setup:rwx /live/persistence/*_unlocked \
+		|| error "Could not set ACL on /live/persistence/*_unlocked: $?"
+
 	# XXX: error out if migration is needed, but read-only was selected.
 	# If live-persistence.conf exists but persistence.conf does not,
 	# then migrate.
 	if ls /live/persistence/*_unlocked/live-persistence.conf >/dev/null 2>&1 \
 	   && ! ls /live/persistence/*_unlocked/persistence.conf >/dev/null 2>&1
 	then
-		# Migrate ownership & permissions for the filesystems.
-		chown root:root /live/persistence/*_unlocked \
-			|| error "Could not chown /live/persistence/*_unlocked"
-		chmod 1777 /live/persistence/*_unlocked \
-			|| error "Could not chmod /live/persistence/*_unlocked"
 		# Disable live-additional-software.conf if it was not migrated yet.
 		for f in /live/persistence/*_unlocked/live-additional-software.conf
 		do
