First stab at making the new NetworkManager configuration directory persistent, when the old one was.

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -323,6 +323,31 @@ activate_volumes ()
 		fi
 	done
 
+	# Migrate Squeeze-era NetworkManager persistence setting to Wheezy.
+	# XXX: keep the old setting in place? Even if we drop it, the data still
+	# is on the persistent volume. Is there an automated importation mechanism?
+	for conf in $(ls /live/persistence/*_unlocked/persistence.conf || true)
+	do
+		if grep -E -qs --line-regex \
+			-e '/home/amnesia/\.gconf/system/networking/connections\s+source=nm-connections' \
+			"$conf" \
+		   && ! grep -E -qs --line-regex \
+			-e '/etc/NetworkManager/system-connections\s+source=nm-system-connections' \
+			"$conf"
+		then
+			warning "Needs to make /etc/NetworkManager/system-connections persistent"
+			if [ "$PERSISTENCE_READONLY" = true ]
+			then
+				# XXX: don't really error-out, do we?
+				error "Persistence configuration needs to be migrated, but read only was selected; please retry in read-write mode"
+			fi
+			echo '/etc/NetworkManager/system-connections	source=nm-system-connections' \
+				>> "$conf" \
+				|| error "Failed to make /etc/NetworkManager/system-connections persistent: $?"
+			warning "Successfully made /etc/NetworkManager/system-connections persistent"
+		fi
+	done
+
 	# Load the new persistence.conf.
 	custom_mounts="$(mktemp /tmp/custom_mounts-XXXXXX.list)"
 	get_custom_mounts ${custom_mounts} ${open_volumes}
