Create empty live-additional-software.conf after disabling the old one.

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -273,6 +273,10 @@ activate_volumes ()
 			then
 				mv "$f" "${f}.disabled" \
 					|| error "Failed to disable unsafe '$f': $?"
+				install --owner tails-persistence-setup \
+					--group tails-persistence-setup --mode 0600 \
+					/dev/null "$f" \
+					|| error "Failed to create empty '$f': $?"
 			fi
 		done
 		# Migrate known-safe settings from old configuration to new one.
