Fix a corner case for the MAC spoofing panic mode.
If panic mode failed to disable the specific device that couldn't be
spoofed (by unloading the module) we disable networking. Previously we
only stopped NetworkManager. The problem is that NM isn't even started
at this time, but will specifically be started when we're done with
MAC spoofing.

Therefore, let's remove NetworkManager so it cannot possibly be
started.

Will-fix: #10160

diff --git a/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac b/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
--- a/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
+++ b/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
@@ -14,6 +14,12 @@ set -e
 TEXTDOMAIN="tails"
 export TEXTDOMAIN
 
+disable_networking() {
+    service network-manager stop || :
+    rm -f /etc/init.d/network-manager /usr/sbin/NetworkManager
+    log "Networking disabled"
+}
+
 show_notification() {
     # We must wait until all the facilities necessary for showing the
     # notification to the Live user is available to prevent it from
@@ -63,8 +69,8 @@ mac_spoof_panic() {
     echo "blacklist ${module}" >> /etc/modprobe.d/"${module}"-blacklist.conf
     unload_module_and_rev_deps "${module}" || :
     if nic_exists "${nic}"; then
-        log "Failed to unload module ${module} of NIC ${nic}. Stopping NetworkManager."
-        service network-manager stop
+        log "Failed to unload module ${module} of NIC ${nic}"
+        disable_networking
         notify_panic_failure "${nic}" "${nic_name}" &
     else
         log "Successfully unloaded module ${module} of NIC ${nic}."
@@ -130,8 +136,8 @@ then
         # If mac_spoof_panic() fails we're quite screwed, so we kill
         # NetworkManager without notification to do our best to
         # prevent a MAC address leak.
-        log "Panic mode failed for NIC ${NIC}. Killing NetworkManager."
-        service network-manager stop
+        log "Panic mode failed for NIC ${NIC}"
+        disable_networking
     fi
     exit 1
 fi
