Some `set -e` hardening.

diff --git a/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac b/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
--- a/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
+++ b/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
@@ -43,12 +43,14 @@ mac_spoof_panic() {
     local nic_name
     local unload_success
     nic=${1}
-    /sbin/ip link set dev "${nic}" down
+    if ! /sbin/ip link set dev "${nic}" down; then
+        log "Failed to down NIC ${nic} in panic mode."
+    fi
     module=$(get_module_used_by_nic "${nic}")
     nic_name="$(get_name_of_nic ${nic})"
     echo "blacklist ${module}" >> /etc/modprobe.d/"${module}"-blacklist.conf
-    unload_module_and_rev_deps "${module}"
-    if [ "$?" -ne 0 ] || lsmod | grep -q "^${module}\s"; then
+    unload_module_and_rev_deps "${module}" || :
+    if lsmod | grep -q "^${module}\s"; then
         service network-manager stop
         log "Failed to unload module ${module} of NIC ${nic}. Stopping NetworkManager."
         notify_panic_failure "${nic}" "${nic_name}" &
