Avoid sub-shelling.
Previously we returned in a sub-shell, which probably didn't do what
we wanted. If anything, this makes the code more readable at least.

diff --git a/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac b/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
--- a/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
+++ b/config/chroot_local-includes/usr/local/sbin/tails-spoof-mac
@@ -39,14 +39,22 @@ macchanger_helper() {
     was_up=no
     if nic_is_up ${nic}; then
         was_up=yes
-        /sbin/ifconfig ${nic} down || ( log "failed to down ${nic}" ; return 1 )
+        if ! /sbin/ifconfig ${nic} down; then
+            log "failed to down ${nic}"
+            return 1
+        fi
     fi
-    ret=0
-    macchanger ${opts} ${nic} || \
-        ( ret=$? ; log "macchanger returned error code ${ret}" )
+    macchanger ${opts} ${nic}
+    ret=$?
+    if [ "${ret}" -ne 0 ]; then
+        log "macchanger returned error code ${ret}"
+    fi
 
     if [ "${was_up}" = yes ]; then
-        /sbin/ifconfig ${nic} up || ( log "failed to up ${nic}" ; return 1 )
+        if ! /sbin/ifconfig ${nic} up; then
+            log "failed to up ${nic}"
+            return 1
+        fi
     fi
     return ${ret}
 }
